[functions]
node_bundler = "esbuild"
[dev]
port = 8989
[build]
# command = "# no build command"
command = "npm run build"
functions = "netlify/functions"
publish = "build"
[[redirects]]
from = "/*"
to = "/.netlify/functions/"
status = 200
